### ISSUE TITLE
Detail Spec of Network Communication and Messaging 

### ISSUE THREAD

**Issue by taeguk** [DrawML/research-dist#2]
There are network communications among a master and workers....
HOW?
implement from bottom(handling socket??)??
or use other good libraries? then what??

MPI??? 

Let's discuss and search and think.

**Comment by taeguk** [comment]
Implementing from bottom(ex.socket..) is very inefficient as i think.
We should search some libraries that do these 'bottom' jobs. @Gnob

**Comment by Gnob** [comment]
Yeah, i think we have to use the [ZeroMQ](http://zeromq.org/) as i mentioned.
It is introduced by official homepage guide,

> ZeroMQ (also known as ØMQ, 0MQ, or zmq) looks like an embeddable networking library but acts like a concurrency framework.

Although it seems that we still use a socket provided by zmq, it is more powerful than raw socket!

We can use zmq efficiency way using a pattern.
Until now, I'm trying to design our architecture as below.

![Architecture](https://github.com/DrawML/research-dist/raw/master/sangbong/img/1_architecture.jpg)

Please give me a feedback.

**Comment by taeguk** [comment]
I agree about your architecture.
But, spliting or merging workers are added to that.
In implementation, and we should remember the worker is virtual concept.

**Comment by taeguk** [comment]
And about ZeroMQ, I have to search more data.
I'm in running bus to go to exercise.
After I arrive home back, I google some data, and then I feedback to you.
Thank you to your comment.

**Comment by taeguk** [comment]
Ah, and more to architecture,
Master, worker....and I think we need one more thing which manages one computer.
It check computer's resource and report that to master.
What do we call it? (naming...l

**Comment by Gnob** [comment]
Worker King? 😆 
or Worker Manager?

It is too hard to name something... 😞

**Comment by Gnob** [comment]
# Resources
- [Quickly and simply overview - Private wiki page](http://www.potatogim.net/wiki/ZeroMQ)
  - You should read extra documents in **See Also** section.
- [Official homepage korean guide](http://kr.zeromq.org/page:read-the-manual)
  - If you need something as official reference, you will find it here.
- [Official zmq practice guide](http://zguide.zeromq.org/)
  - There are explanations and examples how to use zmq practically.

**Comment by taeguk** [comment]
Yo! We are doing real-time communication now!

**Comment by taeguk** [comment]
I look at some materials(http://chiyo85.tistory.com/80). 
I think ZeroMQ seems good. Let's use ZeroMQ!

**Comment by Gnob** [comment]
I think so too, Great! 😄 
Now, we should architect **Worker Manager - Worker**, how to divide or merge logically.
What do you think about that? Have you been thought any policy before?

**Comment by taeguk** [comment]
okay, but naming "Worker Manager" is strange as I think. Master does a role of "Worker Manager"
I think "Computer Manager" or "Resource Manager" or what... are better in aspect of meaning.

**Comment by taeguk** [comment]
About scheduling, let's discuss at #5

**Comment by taeguk** [comment]
Good Examples about ZeroMQ
https://github.com/imatix/zguide/tree/master/examples/Python

**Comment by taeguk** [comment]
Okay, close.
Our distribution nodes are consisted with Master, Slave and (Virtual Concept) Worker.
