### ISSUE TITLE
How to design and implement Protocol?

### ISSUE THREAD

**Issue by taeguk** [DrawML/research-dist#8]
1. simple string type.
2. structured string such as json/xml.
3. raw binary
4. google's protobuf
5. etc....

We need search and discussion.

**Comment by Gnob** [comment]
I think the best choice is protobuf.
Or Thrift is one of choices, although not in the list.

**Comment by taeguk** [comment]
Protobuf vs Thrift.....
I think Thrift is more better aspect of readability and etc....

**Comment by taeguk** [comment]
http://knight76.tistory.com/entry/Thrift-vs-Protocol-Buffers-%EB%B9%84%EA%B5%90%EB%AC%B8-%EC%9A%94%EC%A0%90-%EC%A0%95%EB%A6%AC-%EB%B0%9C%EB%B2%88%EC%97%AD

**Comment by taeguk** [comment]
There is a Apache Avro as a one of choices.

http://debop.blogspot.kr/2013/03/thrift-avro.html

**Comment by Gnob** [comment]
If we don't need the RPC stack, protobuf is better than others.

Probably, Avro is not proper to our project.
One of its strong points is supporting dynamic scheme which i think we don't need.

**Comment by taeguk** [comment]
Good. Now can we consider a point at issue "Protobuf vs Thrift"?
As I comprehend, 
Protobuf is more easily aspect of documentation,
And Thrift is more powerful and good. But there is lack documentation...:(

I want to use Thrift, but I worry about documentation.

**Comment by taeguk** [comment]
Yes. We determine to use Thrift.
Detail Protocol Spec is discussed later.

**Comment by taeguk** [comment]
Change it to use Protobuf.

**Comment by taeguk** [comment]
draft of protocol is assigned to @Gnob
